CREATE DATABASE unnispick;

USE unnispick;

CREATE TABLE member (
	ID_MEMBER BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	USERNAME varchar(255) NOT NULL,
	GENDER varchar(1) NOT NULL,
	SKINTYPE varchar(255),
	SKINCOLOR varchar(255)
);

CREATE TABLE product(
	ID_PRODUCT BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	NAME_PRODUCT varchar(255) NOT NULL,
	PRICE	bigint UNSIGNED NOT NULL
);

CREATE TABLE review_product(
	ID_REVIEW BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	ID_PRODUCT BIGINT UNSIGNED,
	ID_MEMBER BIGINT UNSIGNED,
	DESC_REVIEW LONGTEXT NOT NULL,
	FOREIGN KEY(ID_MEMBER) REFERENCES member(ID_MEMBER),
	FOREIGN KEY(ID_PRODUCT) REFERENCES product(ID_PRODUCT)
);

CREATE TABLE like_review(
	ID_REVIEW BIGINT UNSIGNED,
	ID_MEMBER BIGINT UNSIGNED,
	DESC_REVIEW LONGTEXT NOT NULL,
	FOREIGN KEY(ID_REVIEW) REFERENCES review_product(ID_REVIEW),
	FOREIGN KEY(ID_MEMBER) REFERENCES member(ID_MEMBER)
);